### ISSUE TITLE
Murder Mystery On Disable

### ISSUE THREAD

**Issue by RetroAvenDev** [Plajer-Lair/MurderMystery#5]
[09:07:26 INFO]: [MurderMystery] Disabling MurderMystery v1.1.3
[09:07:26 ERROR]: Error occurred while disabling MurderMystery v1.1.3 (Is it up to date?)
java.lang.NullPointerException: null
        at pl.plajer.murdermystery.Main.onDisable(Main.java:168) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[Spigot_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:371) [Spigot_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at com.massivecraft.massivelag.inject.MassiveLagPluginLoader.disablePlugin(MassiveLagPluginLoader.java:220) [MassiveLag.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:429) [Spigot_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:422) [Spigot_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:370) [Spigot_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:621) [Spigot_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:766) [Spigot_1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by Plajer** [comment]
Support is provided at Discord, issue is no longer revelant on newer versions.
